### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by TurtleShroom** [tannerflick4/PernMod#1]
@tannerflick4 

Good afternoon.

I made an attempt to contact you through E-Mail a few days ago, but I got no response. Do you use the Discord chat room, and if so, would you be willing to speak with me when you get the chance?

If not, would you mind replying to my E-Mail?

Thank you.
-TURTLESHROOM

**Comment by tannerflick4** [comment]
Hey! https://discord.gg/RcywDYY

Theres the link

**Comment by TurtleShroom** [comment]
I hope that our time zones are more favorable than Loup and I are.
